---
abstract: ~
author:
  - 'Matteo Corti <matteo.corti@id.ethz.ch>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: check_free_mem
no_index:
  directory:
    - inc
requires:
  Carp: 0
  English: 0
  File::Slurp: 0
  Getopt::Long: 0
  Nagios::Plugin: 0
  Nagios::Plugin::Threshold: 0
  perl: 5.8.0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.0.1
